### ISSUE TITLE
add AX860i

### ISSUE THREAD

**Issue by okias** [Jon0/ax1600i#1]
Hey! Just adding a note, I'll try to make your code run with AX860i too.

First experiement:
```
self.handle.write_control(0x40, 0x02, 0x0002, 0, &empty, Duration::from_secs(1)).expect("Control failed");
```
isn't same for AX860i, but computer now compiles and usb-serial conventer disappeared, so I need to wait until next re-plug or reboot.

**Comment by Jon0** [comment]
Cool, I started this because ax1600i seems a little different from other models - If this code isn't working some other projects may be useful:
- https://github.com/ka87/cpsumon
- https://github.com/liquidctl/liquidctl
- https://github.com/wgottwalt/corsair-psu

cpsumon looks like it might already work for the AX860i, the models with dongles all work mostly the same, but the AX1600i has no dongle and the protocol is slightly different (seems to add an additional one byte: 0x12 to acknowledge each message)

**Comment by okias** [comment]
Thank you for the tip, `cpsumon` works well, regarding to the design, I'll drop my effort to implement 860i in your repo :)
